-- Add thumbnail fields for guides generated by AI
alter table public.guides
  add column if not exists thumbnail_url text,
  add column if not exists thumbnail_prompt text;

-- Optional index to quickly find guides with thumbnails
create index if not exists guides_thumbnail_url_idx
  on public.guides using btree (thumbnail_url);
